services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tjv'
      - 'POSTGRES_USER=tjv'
      - 'POSTGRES_PASSWORD=tjv'
    ports:
      - '5432:5432'
    volumes:
      - "./cardatabase/src/main/resources/init_scripts:/docker-entrypoint-initdb.d"
